version: '3.9'

services:
  node-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/code:/usr/src/app
    environment:
      NODE_ENV: production
